# Generated by Django 4.2.4 on 2024-04-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_producttag_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="product-thumbnails"),
        ),
    ]
